### ISSUE TITLE
Cauldron 1.7.10 Crashing on New Players

### ISSUE THREAD

**Issue by sman260** [LatvianModder/LatCoreMC#13]
Cauldron Version:  Cauldron-MCPC-Plus-1.7.10-1.1307.06.218
Forge Version:   forge-1.7.10-10.13.2.1291-universal

We are having an issue that when people are logged in and a player who has not been on the server yet log in it kicks everyone out of the server except the new player.   It looks like this was a known issue back in January with an earlier version.    

```
[B#283]  [14:58:40] [Client thread/INFO]: [CHAT] Drowshire joined the game.
[B#283]  [14:58:40] [Client thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
[B#283]  java.lang.NullPointerException
[B#283]  	at latmod.core.net.MessageUpdateLMPlayer.onMessage(MessageUpdateLMPlayer.java:31) ~[MessageUpdateLMPlayer.class:?]
[B#283]  	at latmod.core.net.MessageUpdateLMPlayer.onMessage(MessageUpdateLMPlayer.java:7) ~[MessageUpdateLMPlayer.class:?]
[B#283]  	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
[B#283]  	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
[B#283]  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
[B#283]  	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
[B#283]  	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
[B#283]  	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[B#283]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[B#283]  	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[B#283]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
[B#283]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[B#283]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[B#283]  [14:58:40] [Client thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
[B#283]  java.lang.NullPointerException
[B#283]  	at latmod.core.net.MessageUpdateLMPlayer.onMessage(MessageUpdateLMPlayer.java:31) ~[MessageUpdateLMPlayer.class:?]
[B#283]  	at latmod.core.net.MessageUpdateLMPlayer.onMessage(MessageUpdateLMPlayer.java:7) ~[MessageUpdateLMPlayer.class:?]
[B#283]  	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
[B#283]  	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
[B#283]  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
[B#283]  	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
[B#283]  	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
[B#283]  	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[B#283]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[B#283]  	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[B#283]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
[B#283]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[B#283]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[B#283]  [14:58:40] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel LatCoreMC
[B#283]  java.lang.NullPointerException
[B#283]  	at latmod.core.net.MessageUpdateLMPlayer.onMessage(MessageUpdateLMPlayer.java:31) ~[MessageUpdateLMPlayer.class:?]
[B#283]  	at latmod.core.net.MessageUpdateLMPlayer.onMessage(MessageUpdateLMPlayer.java:7) ~[MessageUpdateLMPlayer.class:?]
[B#283]  	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
[B#283]  	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
[B#283]  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
[B#283]  	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[B#283]  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
[B#283]  	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
[B#283]  	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[B#283]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[B#283]  	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[B#283]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
[B#283]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[B#283]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[B#283]  [14:58:40] [Netty Client IO #2/INFO] [THAUMCRAFT]: Restoring client configs.
[B#283]  [14:58:40] [Netty Client IO #2/INFO] [Galacticraft]: Unregistered Dimension: -30
[B#283]  [14:58:40] [Netty Client IO #2/INFO] [Galacticraft]: Unregistered Dimension: -29
[B#283]  [14:58:40] [Netty Client IO #2/INFO] [Galacticraft]: Unregistered Dimension: -40
[B#283]  [14:58:40] [Netty Client IO #2/INFO] [Galacticraft]: Unregistered Dimension: -59
[B#283]  [14:58:40] [Netty Client IO #2/INFO] [Galacticraft]: Unregistered Dimension: -41
[B#283]  [14:58:40] [Netty Client IO #2/INFO] [Galacticraft]: Unregistered Dimension: -45
[B#283]  [14:58:40] [Netty Client IO #2/INFO] [Galacticraft]: Unregistered Dimension: -57
[B#283]  [14:58:40] [Netty Client IO #2/INFO] [Galacticraft]: Unregistered Dimension: -47
[B#283]  [14:58:40] [Netty Client IO #2/INFO] [Galacticraft]: Unregistered Dimension: -28
[B#283]  [14:58:40] [Netty Client IO #2/INFO] [mcjty.rftools.RFTools]: Disconnect from server: Unregistering RFTools dimensions
[B#283]  [14:58:40] [Netty Client IO #2/INFO] [OpenMods]: openmods.network.IdSyncManager.onDisconnect(IdSyncManager.java:124): Disconnected, restoring local data
[B#283]  [14:58:40] [Client thread/INFO]: [CHAT] Drowshire has just earned the achievement [You've been installed!]
[B#283]  [14:58:40] [Client thread/INFO] [STDOUT]: [mcjty.rftools.dimension.network.SyncDimensionInfoHelper:syncDimensionManagerFromServer:15]: SYNC DIMENSION STUFF: world.isRemote = true
[B#283]  [14:58:40] [Client thread/INFO] [mcjty.rftools.RFTools]: RfToolsDimensionManager.syncFromServer
[B#283]  [14:58:40] [Client thread/INFO] [mcjty.rftools.RFTools]: Dimension information from server is empty.
[B#283]  [14:58:40] [Client thread/INFO] [FML]: Applying holder lookups
[B#283]  [14:58:40] [Client thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[B#283]  [14:58:40] [Client thread/WARN] [FML]: Unable to lookup chisel:obsidian2 for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.obsidian2. Is there something wrong with the registry?
[B#283]  [14:58:40] [Client thread/WARN] [FML]: Unable to lookup CompactMachines:interfaceblock for public static org.dave.CompactMachines.block.BlockCM org.dave.CompactMachines.init.ModBlocks.interfaceblock. Is there something wrong with the registry?
[B#283]  [14:58:40] [Client thread/INFO] [FML]: Holder lookups applied
[B#283]  [14:58:42] [Client thread/INFO] [MapWriter]: Mw.close: closing...
[B#283]  [14:58:42] [Client thread/INFO] [MapWriter]: waiting for 207 tasks to finish...
[B#283]  [14:58:44] [Client thread/INFO] [MapWriter]: done
```

**Comment by LatvianModder** [comment]
Yes, I already noticed and probably fixed (didn't have time to test yet), thanks for the report anyway, should be fixed in https://github.com/LatvianModder/LatCoreMC/commit/98b24652a5a6fd48a1ce7391d47275b3283a19fa (upcoming version 1.6.9)
